# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Desenvolvimento com frameworks e componentes
email: michel.vasconcelos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site do conteúdo da disciplina de especialização da FA7 sobre Desenvolvimento
  Corporativo com frameworks e componentes.
baseurl: "/uni7-frameworks" # the subpath of your site, e.g. /blog
url: "http://michelav.github.io/fa7-frameworks" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown

# Collections
collections:
  presentations:
    output: true
